const CONTENTS_FRAME_MAX_COL = 4;
const CONTENTS_FRAME_MAX_ROW = 8;
const IMAGE_CONTENTS_NUM_NEXT_PAGE = 10;

const CONTENTS_RECEIVER_MAX_HEIGHT_PX = 150;
const CONTENTS_RECEIVER_MAX_WIDTH_PX = 400;
